### ISSUE TITLE
Running the R client on computers with restrictions to install software

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-r-client#19]
Public authorities / NGOs / companies may have restrictions to install software (as e.g. Python, R) on their office computers. A remotely hosted openEO web editor is a way for them also to use openEO, but is it also possible to run the openEO client using a portable R installation? Would be nice to check this and add a hint to the documentation.

**Comment by GreatEmerald** [comment]
Also relates to #21.

**Comment by flahn** [comment]
Found [this](https://sourceforge.net/projects/rportable/). But I don't know if it solves the issue, because at some point you need to install something or at least execute a downloaded executable file or extract it.

I cannot test the installation of the mentioned tool, since it says that it is not recommended to install it with an already existing R installation.

**Comment by GreatEmerald** [comment]
At the hackathon it was mentioned that those restricted computers cannot even use portable software (including conda etc.), because they can't even upload arbitrary files without authorisation... So the web interface would be the only way to do it.

**Comment by flahn** [comment]
Maybe this is from interest in this regard:
https://www.r-bloggers.com/r-binder-interactive-jupyter-notebooks-in-the-cloud/
