### ISSUE TITLE
Performance of describeCollection across OSs

### ISSUE THREAD

**Issue by GreatEmerald** [Open-EO/openeo-r-client#22]
There are some odd issues with the performance of the `describeCollection` function. On Linux, with `rgdal` installed, it is instantaneous. On Windows without `rgdal` installed, it is extremely slow. On Windows with `rgdal` installed, it is also instantaneous. And on macOS with `rgdal` installed, it is slow (not quite as slow as on Windows, seemingly, but still uncomfortably slow).

What could be causing that and is there anything that could be done about it?

**Comment by flahn** [comment]
When describing a collection the `client.R` fetches the metadata for that particular collection. Before returning the data, however, I try to convert the extent, the srs and the timestamps into usable R objects like Extent, CRS and POSIXct. My guess is that resolving the EPSG code into a CRS GDAL is utilized (gdalsrsinfo). The reason is that we need to access GDALs internal PROJ4 library to get the particular information.

We can ignore it, but then it cannot be visualized on the map.

**Comment by GreatEmerald** [comment]
I see. (Why do we even use EPSG codes instead of proj4strings to begin with...)

Maybe it would be possible to do something akin to what `raster` does, and only use functions that are GDAL-based when GDAL is available? Otherwise fall back to something simpler. (The list of EPSG codes that are in practice used on the backends probably isn't that large...)

**Comment by flahn** [comment]
I checked the dependencies and decided to switch to package `sp` for handling the bounding box. `sp` provided also functions to create a CRS (proj4string) from EPSG codes. So that I were able to remove dependencies to `raster`, `rgdal` and `gdalUtils`. If the downloaded results shall be shown or loaded into R, then the user needs to take care of it by themselves, but that should be fine.

**Comment by GreatEmerald** [comment]
Can `sf` be used instead of `sp` in this case? I'd imagine it should include all the needed functionality as well (@edzer?).

**Comment by flahn** [comment]
This issue has gone stale. Closing this for now.
