### ISSUE TITLE
download_results() should return the downloaded filename

### ISSUE THREAD

**Issue by GreatEmerald** [Open-EO/openeo-r-client#32]
Currently, `download_results()` doesn't return anything. That makes it guesswork as to what file it downloaded. It should return the filename(s?).

**Comment by flahn** [comment]
It is currently implemented that you can specify a folder, where all the processed data is downloaded into. The file naming is the same as it is on the back-end. I simply browse through the stated `links` with the fields `href` and `type`. Then I take the filename from the value of the `href`. I implemented it that way, because we can have multiple files and you either provide a user defined name for each of the files (in order) or you simply take the potentially cryptic filename from the back-end.

The function returns simple TRUE as invisible (not printed). I see your point that it makes it easier for a user to get a list or vector of file paths as return value.
