### ISSUE TITLE
Simplifications?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-r-client#43]
I'm looking at the GEE example and I'm confused about some things:

```r
library(openeo)
library(magrittr)
library(tibble)
library(jsonlite)
```
It doesn't seem that I'm directly using any of the non openeo dependencies. Why do I need to import them myself? Wouldn't it be easier that `library(openeo)` simply imports everything needed?

```r
con = connect(host = gee_host_url, version="0.4.2", user = user, password = pwd, login_type = "basic")
```
Why do I have to set the version? 0.4.2 is the "default" for GEE and should be discovered through the well known discovery mechanism.

```r
graph = process_graph_builder(con = con)
```
Could this be: `con$process_graph_builder()`? Also, can we get rid of the process graph word for the next version?

```r
data = graph$load_collection(graph$data$`COPERNICUS/S2`, ...)
```
What is this `graph$data$COPERNICUS/S2`? Seems not very intuitive, I'd expect `"COPERNICUS/S2"` as string.

```r
spectral_reduce = graph$reduce(data = data, dimension = "bands",reducer = function(x) {
  B08 = x[1]
  B04 = x[2]
  B02 = x[3]
  (2.5 * (B08 - B04)) / sum(B08, 6 * B04, -7.5 * B02, 1)
})
```
Why can one use simply `sum` in the callback, but not in the "top level" code? There it would be `graph$sum`, I guess? That seems counter-intuitive. On the other hand, the linear transform below uses `graph$linear_scale_range` and not just `linear_scale_range`. Confusing.

```r
temporal_reduce = graph$reduce(data = spectral_reduce,dimension = "temporal", reducer = function(x) {
  min(x)
})
```
Would it be possible to do something like `reducer = min(x)` or `reducer = min` if parameters match?

```r
  graph$linear_scale_range(x = value, 
                           inputMin = -1, 
                           inputMax = 1, 
                           outputMin = 0, 
                           outputMax = 255)
```
A general R question: Could this simply be `graph$linear_scale_range(value, -1, 1, 0, 255)` as an alternative if one likes it more compact?

```r
compute_result(con=con,graph=graph,format = "PNG",output_file = "gee_evi_example.png")
```
Comparing to the example above with `graph$data$COPERNICUS/S2`, could I use something like `format = graph$output_format$PNG` here? (Not saying this is better than simply "PNG".)

Thanks :-)

**Comment by flahn** [comment]
Everything listed here references to the feature branch "callback_simplification", which I am currently working on.

I can quickly answer some of the questions. Other things are good points and I have to investigate this and implement it during the next weeks.

> ```r
> library(openeo)
> library(magrittr)
> library(tibble)
> library(jsonlite)
> ```
> 
> It doesn't seem that I'm directly using any of the non openeo dependencies. Why do I need to import them myself? Wouldn't it be easier that `library(openeo)` simply imports everything needed?
>

Yes and no. You can simply use openeo, yes. I guess some of them are relicts, because I used those package in other scripts at some point. `magrittr` with the pipe operators `%>%` I wrote off the last days and can be safely removed. For the package `openeo` to work it will load the imported namespaces, but in other scripts I had to use some of the functions in the package and therefore I had to load them explicitly.

> ```r
> con = connect(host = gee_host_url, version="0.4.2", user = user, password = pwd, login_type = "basic")
> ```
> 
> Why do I have to set the version? 0.4.2 is the "default" for GEE and should be discovered through the well known discovery mechanism.

Yes, you are right. I have to look at this.

> 
> ```r
> graph = process_graph_builder(con = con)
> ```
> 
> Could this be: `con$process_graph_builder()`? Also, can we get rid of the process graph word for the next version?
> 

This will change. I don't know exactly how it will look like, but it will change ;) Usually R users are not that familiar with the notion `con$process_graph_builder()` and I tried to avoid this, except of the process graph handling.
Currently this is also confusing, because the process_graph_builder function returns a Graph object. I will also change this in the future.

> ```r
> data = graph$load_collection(graph$data$`COPERNICUS/S2`, ...)
> ```
> 
> What is this `graph$data$COPERNICUS/S2`? Seems not very intuitive, I'd expect `"COPERNICUS/S2"` as string.
> 

Oh, you can pass a String. But I am lazy and use auto completion ;) `graph$data$COPERNICUS/S2` returns the String "COPERNICUS/S2"

> ```r
> spectral_reduce = graph$reduce(data = data, dimension = "bands",reducer = function(x) {
>   B08 = x[1]
>   B04 = x[2]
>   B02 = x[3]
>   (2.5 * (B08 - B04)) / sum(B08, 6 * B04, -7.5 * B02, 1)
> })
> ```
> 
> Why can one use simply `sum` in the callback, but not in the "top level" code? There it would be `graph$sum`, I guess? That seems counter-intuitive. On the other hand, the linear transform below uses `graph$linear_scale_range` and not just `linear_scale_range`. Confusing.

The main reason linear_scale_range has to be called from the back-ends processes is that I haven't found a generic / primitive function to overload. 

The "top level" thing has to be tested, but I guess that does not work yet. If it is doable, I will consider it for a change. Generally, there is a huge difference between the processes and the overloaded R functions. Mainly, the overloaded R function have a different signature than the processes we have defined in openEO.

> 
> ```r
> temporal_reduce = graph$reduce(data = spectral_reduce,dimension = "temporal", reducer = function(x) {
>   min(x)
> })
> ```
> 
> Would it be possible to do something like `reducer = min(x)` or `reducer = min` if parameters match?

`min(x)` won't work because R can't evaluate the unset parameter x. `min` might work, but this is the "top level" thing you mentioned previously.

> 
> ```r
>   graph$linear_scale_range(x = value, 
>                            inputMin = -1, 
>                            inputMax = 1, 
>                            outputMin = 0, 
>                            outputMax = 255)
> ```
> 
> A general R question: Could this simply be `graph$linear_scale_range(value, -1, 1, 0, 255)` as an alternative if one likes it more compact?

You can do that, but than the ordering of the parameters is essential. I had examples of other back-ends that sorted the parameters alphabetically and this failed hard.

> 
> ```r
> compute_result(con=con,graph=graph,format = "PNG",output_file = "gee_evi_example.png")
> ```
> 
> Comparing to the example above with `graph$data$COPERNICUS/S2`, could I use something like `format = graph$output_format$PNG` here? (Not saying this is better than simply "PNG".)

Might be worth to have a look.

**Comment by m-mohr** [comment]
Thanks. The order of the parameters is defined since 0.4 with improvements in 1.0. So if things fail due to the order it's a backend issue.

**Comment by flahn** [comment]
> > ```r
> > con = connect(host = gee_host_url, version="0.4.2", user = user, password = pwd, login_type = "basic")
> > ```
> > 
> > 
> > Why do I have to set the version? 0.4.2 is the "default" for GEE and should be discovered through the well known discovery mechanism.
> 
> Yes, you are right. I have to look at this.
> 

I'm not sure, but I could find anything about a default implementation - neither in the 0.4.2 nor 1.0.0 API. There is something about "production" readiness, but apart from that there is nothing. 

In the R client this is currently handled in the following ways:
1. if you pass a direct link (where capabilities are called) as host you don't need a version
2. if you have the link to the well-known doc you may pass a version, then the direct link is read from the document
3. you don't pass a version in 2., then you will get an overview printed about the available versions

**Comment by m-mohr** [comment]
The intended behavior is that it connects by default to the highest version number  (semver) with production set to true.

**Comment by flahn** [comment]
> 
> Why can one use simply `sum` in the callback, but not in the "top level" code? There it would be `graph$sum`, I guess? That seems counter-intuitive. [...]
> 
> ```r
> temporal_reduce = graph$reduce(data = spectral_reduce,dimension = "temporal", reducer = function(x) {
>   min(x)
> })
> ```
> 
> Would it be possible to do something like `reducer = min(x)` or `reducer = min` if parameters 

Just tested this behavior and it does work. You can either pass `min` or `graph$min` as a parameter. But it has to be a function in R. The function will be evaluated with the former callback parameter. Similarly it will also work with other native aggregation functions.

When I try this with the linear scale range part, it does not work. If you have to pass additional values into the process it has to be within an externally wrapped function. It would however work using only `graph$linear_scale_range`, but then you don't have any values in there. As soon as you would use `graph$linear_scale_range()` you would execute the function and you will have a return value and not a function definition passed on.
