### ISSUE TITLE
`describe` requires specifying whether it is a product or a process

### ISSUE THREAD

**Issue by GreatEmerald** [Open-EO/openeo-r-client#6]
This is a small discussion point: at the moment, the `describe` function requires the user to say whether they want a description of a product or a process via arguments. However, this is not very convenient, because one needs to put `product_id` always when trying to describe products (and that's not needed to describe processes). And while it's neat to be able to describe several things at a time, is that functionality really useful?

Perhaps it would be better to have something like separate `describeProcess` and `describeProduct` functions to make this more uniform.

**Comment by flahn** [comment]
This is a good point. I have also stumbled upon this issue with `describe` and i totally agree that it feels clunky. I can implement it as two separate describe functions.

I will name those functions `describeProcess` and `describeCollection`, since we haven't used the notion "product" anywhere else.

**Comment by GreatEmerald** [comment]
Yes, that's a good point too.
