### ISSUE TITLE
Problems with passing geometries to `aggregate_spatial`

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-r-client#64]
I'm trying to pass geometries in `aggregate_spatial`, and it seems that this fails when the passed sf objects don't have any attributes. I'm creating geometries from a GeoJSON string with package geojsonsf like so:
```
library(geojsonsf)
pol_str <- '{ "type": "FeatureCollection", "features": [ { "type": "Feature", "properties": {}, "geometry": { "type": "Polygon", "coordinates": [ [ [ 5.636715888977051, 52.6807532675943 ], [ 5.629441738128662, 52.68157281641395 ], [ 5.633561611175536, 52.67787822078012 ], [ 5.636715888977051, 52.6807532675943 ] ] ] } }, { "type": "Feature", "properties": {}, "geometry": { "type": "Polygon", "coordinates": [ [ [ 5.622982978820801, 52.68595649102906 ], [ 5.6201934814453125, 52.68429152697491 ], [ 5.628776550292969, 52.683719180920846 ], [ 5.622982978820801, 52.68595649102906 ] ] ] } } ]}'
pols <- geojson_sf(pol_str)
```
to then aggregate
`cube_s2_b8_agg <- p$aggregate_spatial(data = cube_s2_b8, reducer = function(data, context) { p$mean(data) }, geometries = pols)
`
which, upon job submission, fails with a JSON parsing error.
![Screenshot from 2021-06-01 17-27-21](https://user-images.githubusercontent.com/45635480/120349828-b808d380-c2fe-11eb-9acb-275a70dcc011.png)

Everything works if I simply add attributes to the sf object (it contains two polygons):
`pols$A <- c(4,5)`

This seems impractical. Just wanted to report / document the work-around / ask for the reason causing this.

**Comment by flahn** [comment]
Thanks for the report. Interesting case. 
```
> class(pols)
[1] "sf"         "data.frame"
```

I'm not sure if all sf objects inherit also from data.frame or if this is a special circumstance when using geojson_sf. That might point in the direction that adding attributes helps, because otherwise the data.frame would be empty. I'm not sure if I can fix this. Maybe I can include a work-around of some sort behind the scenes. I will keep that in mind.

**Comment by jonathom** [comment]
Additionally, the aggregation doesn't yield the exact same results as if the same `FeatureCollection` is submitted via python or js client. This seems to be because coordinates are rounded in R client somewhere. The `sf` seems fine after converting via `geojsonsf`, only when saving as process graph the coordinates are rounded.

See these lines of the process graph, representing the first coordinates each:
R
```
                    [
                      5.6367,
                      52.6808
                    ],
```
JS
```
                    [
                      5.636715888977051,
                      52.6807532675943
                    ],
```

**Comment by flahn** [comment]
The geometries are serialized into text. At that point either the default amount of digits `options(digits=...)` is used or you can set the precision of the geometry with [`st_precision`](https://r-spatial.github.io/sf/reference/st_precision.html). Maybe the package geojsonsf also sets some default precision.

**Comment by flahn** [comment]
During serialization of JSON with jsonlite there was an default value on the number of digits to be used for numbers. Explicitly settint `digit=NA` during serialization removes the digit cap. 

Other than that in future versions of `openeo` users shall use `sf` objects instead of a GeoJSON representation, as there are too many packages that deal with loading GeoJSON and they all return different kinds of geojson like objects that are hard to offer steady support to.
