### ISSUE TITLE
Run R-Client in Jupyter Notebooks

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-r-client#95]
| Title | Run R-Client in Jupyter Notebooks |
| --- | --- |
| Date | 2021-11-18 |
| Issue | https://github.com/Open-EO/openeo-r-client/issues/95 |
| Category | Usability, integration openEO platform |
| Description | OpenEO platform hosts jupyter notebooks as the default entry point for programming on the platform. To facilitate the uptake of the R-Client in openEO platform it should be verified that the R-Client runs in jupyter notebooks when using R as the kernel and that all visualizations work as in R-Studio. |
| Dependencies | Jupyter, Device Code Authentication |
| Links |  Integration of Vue components, mapview in jupyter |
| Priority | Medium |
| Impact | Medium |

**Comment by przell** [comment]
Tested by @m-mohr. Works for discovery. 
Need Auth #76 
Visualization of Vue components will be solved with #91

**Comment by m-mohr** [comment]
Although in principle we now have supprot for visualizations in Jupyter, there are still some uncertainties about the auth procedure. Right now it works, but once we migrate back to the httr2 code, it may break again due to this issue: https://github.com/r-lib/httr2/issues/111

**Comment by m-mohr** [comment]
`rlang::with_interactive(login())` does work always (but is cumbersome to document for us and people may forget it).

```
rlang::local_interactive()
login()
```
Seems to be unreliable. Sometimes it works, sometimes it does not work. Calling login twice usually works. So it looks like local_interactive needs more time to take effect. Strange. Do you have a clue why that is, @flahn ? Is it because of what is documented for the "frame" parameter? "When the function returns, the options are reset to their original values."

**Comment by m-mohr** [comment]
Created a solution in PR #119
